---
- name: Include Ansible OS family variables.
  ansible.builtin.include_vars: "{{ ansible_facts.os_family }}.yml"
  tags:
    - always

- name: Include agent installation tasks.
  ansible.builtin.include_tasks: install_agent.yml
  tags:
    - install_agent

- name: Test for the agent host key from a previous provisioning.
  ansible.builtin.stat:
    path: /var/alertlogic/etc/host_key.pem
  register: agent_provisioned
  tags:
    - configure_al_agent
    - provision_al_agent

- name: Include agent optional configuration tasks.
  ansible.builtin.include_tasks: configure_agent.yml
  tags:
    - configure_al_agent

- name: Include agent provisioning tasks.
  ansible.builtin.include_tasks: provision_agent.yml
  tags:
    - provision_al_agent

- name: Include configuration steps required for log collection in Linux.
  ansible.builtin.include_tasks: configure_loggers.yml
  tags:
    - provision_al_agent

- name: Include check for SELinux policy requirements.
  ansible.builtin.include_tasks: selinux.yml
  tags:
    - selinux

- name: Start the Alert Logic Agent service.
  ansible.builtin.service:
    name: al-agent
    state: started
    enabled: true
  tags:
    - install_al_agent
  when: not al_agent_for_imaging
