---
- name: Insert/Update syslog-ng.conf for inclusion of alertlogic.conf.
  ansible.builtin.lineinfile:
    path: /etc/syslog-ng/syslog-ng.conf
    regexp: /etc/syslog-ng/conf.d/alertlogic.conf
    line: "include '/etc/syslog-ng/conf.d/alertlogic.conf';"
  notify:
    - Reload syslog-ng.
  tags:
    - syslog_ng
  when: syslog_ng_init is success

- name: Ensure alertlogic.conf file is in place for syslog-ng.
  ansible.builtin.template:
    src: etc/syslog-ng/alertlogic.conf
    dest: /etc/syslog-ng/conf.d/alertlogic.conf
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload syslog-ng.
  tags:
    - syslog_ng
  when: syslog_ng_init is success
