---
- name: Validate role variables.
  ansible.builtin.import_tasks: assert.yml
  tags:
    - always

- name: Include Windows tasks.
  ansible.builtin.include_tasks: _windows.yml
  when: ansible_os_family == "Windows"
  tags:
    - windows

- name: Include Linux tasks.
  ansible.builtin.include_tasks: _linux.yml
  when: ansible_os_family != "Windows"
  tags:
    - al_agent
