---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Update the apt cache.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      register: apt_cache_result
      retries: 3
      until: apt_cache_result is success
      when: ansible_os_family == "Debian"

  roles:
    - role: deekayen.alagent
